### ISSUE TITLE
Status icon

### ISSUE THREAD

**Issue by wabiloo** [kpshek/microsoft-teams-applescripts#4]
Hi,
Do you know if there is a way (via Applescript) to determine current status of mic/camera, in order to set the icon accordingly?

**Comment by kpshek** [comment]
Hi @wabiloo - thanks for the issue. [Microsoft has released a native Teams plugin for the Elgato Stream Deck yesterday](https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/teams-plugin-for-elgato-stream-deck-re-released-also-run-with/ba-p/3767650) which has obsoleted the need for my repository. So, I'm going to archive this repository in favor of the official plugin (which also adds a lot more great features).
