### ISSUE TITLE
Commands won't fire across virtual desktops

### ISSUE THREAD

**Issue by jski** [kpshek/microsoft-teams-applescripts#5]
Hello! 

I'm often in a second virtual desktop during meetings, working on something and watching the Teams meeting in a small window to the side. In this case, the script cannot seem to tab into the meeting, make the change, and tab back. The window does highlight and change focus, but no change is applied. Is this something possible to implement with applescript? Would be very useful.

**Comment by kpshek** [comment]
Hi @jski - thanks for the issue. [Microsoft has released a native Teams plugin for the Elgato Stream Deck yesterday](https://techcommunity.microsoft.com/t5/healthcare-and-life-sciences/teams-plugin-for-elgato-stream-deck-re-released-also-run-with/ba-p/3767650) which has obsoleted the need for my repository. So, I'm going to archive this repository in favor of the official plugin (which also adds a lot more great features).
